### ISSUE TITLE
Builds failing.

### ISSUE THREAD

**Issue by webbrandon** [kubernetes-incubator/descheduler#121]
Not to sure if this is an issue for anyone else but in order to build and run out of box I had to update the `Dockerfile` it build `FROM debian:stretch-slim` in order to run with`/bin/sh`.

**Comment by aveshagarwal** [comment]
> Not to sure if this is an issue for anyone else but in order to build and run out of box I had to update the `Dockerfile` it build `FROM debian:stretch-slim` in order to run with`/bin/sh`.

I have not seen other reports of this issue, could you tell what exact changes you made to fix your issue?
