### ISSUE TITLE
Question about on how pods are evicted

### ISSUE THREAD

**Issue by roldancer** [kubernetes-incubator/descheduler#122]
Hi, I would like to know if it possible to define deschedule policies only for namespaces with a specific label, any idea ?

Thanks.

**Comment by aveshagarwal** [comment]
> Hi, I would like to know if it possible to define deschedule policies only for namespaces with a specific label, any idea ?
> 
> Thanks.

Not in current implementation. Could you describe your use case why would you want to have that? In general, descheduler's aim to rebalance overall cluster, sometimes a set of nodes in a cluster. The thing you are looking for seems like just eviction of pods in namespaces with specific labels. So its possible, but we would have to make sure its use case does not conflict with the real goals of descheduler.
