### ISSUE TITLE
Is there a plan on "Integration with metrics providers for obtaining real load metrics"

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes-incubator/descheduler#123]
I found this feature from the roadmap and I thought it involves real-time scheduling which is quite different from the current logic.

**Comment by aveshagarwal** [comment]
> I found this feature from the roadmap and I thought it involves real-time scheduling which is quite different from the current logic.

Yes, so to have this feature in descheduler, first it would require that default scheduler also supports scheduling based on actual usage of resources.
