### ISSUE TITLE
/bin/sh not found when using this image in kubernetes job

### ISSUE THREAD

**Issue by ykfq** [kubernetes-incubator/descheduler#133]
The `descheduler` will be run as a job in kube-system namespace,  and the command is
```yaml
    Command:
      /bin/sh
      -ec
      /bin/descheduler --policy-config-file /policy-dir/policy.yaml
```
So, there should be a `/bin/sh` binary in the container, but the image was build from sratch and didn't include it.  We can find this from [Dockerfile](https://github.com/kubernetes-incubator/descheduler/blob/v0.8.0/Dockerfile):
```yaml
FROM scratch

MAINTAINER Avesh Agarwal <avagarwa@redhat.com>

COPY --from=0 /go/src/github.com/kubernetes-incubator/descheduler/_output/bin/descheduler /bin/descheduler

CMD ["/bin/descheduler", "--help"]
```
And we got the Error:
> Error: failed to start container "descheduler": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory"

This makes the pod runs into `ContainerCannotRun` state and the job create a new pod immediatly, 
several minutes later I got hundreds of pods and my small cluster finally went down for no responding.
![image](https://user-images.githubusercontent.com/20741596/51370836-58e20400-1b33-11e9-8900-4be871cc2375.png)

![image](https://user-images.githubusercontent.com/20741596/51371183-68158180-1b34-11e9-83b5-b20a2faf91bb.png)

**Comment by zegl** [comment]
Remove the `/bin/sh -ec` part of the command, and it should start correctly.

You should also set `startingDeadlineSeconds` and `concurrencyPolicy` on your CronJob, to avoid a failing job from consuming all of the resources in your cluster.

**Comment by ykfq** [comment]
> Remove the `/bin/sh -ec` part of the command, and it should start correctly.
> 
> You should also set `startingDeadlineSeconds` and `concurrencyPolicy` on your CronJob, to avoid a failing job from consuming all of the resources in your cluster.

Thanks @zegl 
So we should make some updates of the README document.

**Comment by ravisantoshgudimetla** [comment]
@ykfq - Do you mind creating a PR to address this issue?

**Comment by aveshagarwal** [comment]
Fixed in: https://github.com/kubernetes-incubator/descheduler/pull/137
