### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by stevvooe** [kubernetes-incubator/descheduler#138]
I've seen a few issues come by asking questions in this space but didn't see much of a response. It would be good to know the following:

1. Who are the active maintainers?
2. What SIG is responsible for the road map of this project?
3. What is the release cycle?
4. How are releases performed?
5. What stage of the incubation process is this project?
6. Has this project been supplanted by other projects or core features?

I do understand this may be documented elsewhere, but wanted to get some up to date information. If there are ways I could help to get this resolved, I'll also try to help where I can.

**Comment by aveshagarwal** [comment]
> I've seen a few issues come by asking questions in this space but didn't see much of a response. It would be good to know the following:
> 
> 1. Who are the active maintainers?

Myself and Ravi have been actively involved, though others have contributed too as you can see in the commits history.

> 2. What SIG is responsible for the road map of this project?

sig-scheduling.

> 3. What is the release cycle?

There is no specific release cycle. Though the plan is to match its release cycle with kube release cycle.

> 4. How are releases performed?

So far its as simple as creating a new tag and release in github.

> 5. What stage of the incubation process is this project?

I think its not applicable anymore in my understanding as right now, a project can stay in kubernetes-incubator forever as per my last information. But there is a plan to move it to sig specifc repo: https://github.com/kubernetes-incubator/descheduler/issues/132. This project is being shipped as part of openshift too.

> 6. Has this project been supplanted by other projects or core features?

I am not aware so i dont think so.

> I do understand this may be documented elsewhere, but wanted to get some up to date information. If there are ways I could help to get this resolved, I'll also try to help where I can.

Your help in any form is appreciated. Please feel free to contribute in whatever way you can.

Let me know if you need more information.

**Comment by stevvooe** [comment]
Thanks for the great response!
