### ISSUE TITLE
Node roles

### ISSUE THREAD

**Issue by anton-johansson** [kubernetes-incubator/descheduler#139]
In my understanding, some of the policies that `descheduler` uses to evict pods are based on nodes. Node utilization, for example. I have two different roles in my cluster, `worker` and `nginx`. The `nginx` role will only ever have three pods:
* `flannel` (or whatever pod networking we use)
* `filebeat` (gather logs)
* `nginx-ingress-controller` (handle ingresses)

Wouldn't descheduler always consider those nodes under-utilized? Or does `descheduler` respect the `nodeSelector` property of the pods' deployment/statefulset/daemonset?

Or is there a way of configuring which nodes `descheduler` should look at?

**Comment by aveshagarwal** [comment]
yes descheuler has a command line flag `--node-selector` to target only selected nodes.

**Comment by anton-johansson** [comment]
Cool, I can see that here:
https://github.com/kubernetes-incubator/descheduler/blob/d73471327b6737a3c85b4edd6416b0df654ceaab/cmd/descheduler/app/options/options.go#L56-L57

Is there any "official" documentation for `descheduler`? Any webpage, wiki-page, or something similar? Or maybe it will be added to Kubernetes official docs whenever #132 is dealt with?

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes-incubator/descheduler/blob/master/README.md. 
Please feel free to send a PR.
