### ISSUE TITLE
Allow descheduling pods with local storage

### ISSUE THREAD

**Issue by Nowaker** [kubernetes-incubator/descheduler#141]
`IsEvictable` prevents our pods from being descheduled because `IsPodWithLocalStorage` returns `true` ([code](https://github.com/kubernetes-incubator/descheduler/blob/master/pkg/descheduler/pod/pods.go#L130)).

In our case, all Kubernetes nodes are guaranteed to have the requested path available, and the contents are read-only. In other words, it's safe to evict pods with local storage in our case.

Are you guys planning to at least allow a per-pod override to allow eviction of pods with local storage?

**Comment by alenkacz** [comment]
would an annotation be possibly a solution here?

**Comment by Nowaker** [comment]
That would sure do.

**Comment by aranair** [comment]
There's an open PR for this, albeit semi abandoned. https://github.com/kubernetes-incubator/descheduler/pull/120/files

I'm making some small changes and testing that^

**Comment by aveshagarwal** [comment]
https://github.com/kubernetes-incubator/descheduler/pull/142 is merged.

**Comment by Nowaker** [comment]
It's worked for us for weeks! Thanks.
