### ISSUE TITLE
Which version of kuberenetes will have this project included?

### ISSUE THREAD

**Issue by chandrakanthkannam** [kubernetes-incubator/descheduler#152]
Hi,

We have the Kubernetes running on AWS EKS infrastructure and the version is 1.12. we got in to situation where we had to add a new worker node to our existing cluster, but after adding the node the load ( i mean pods) are not getting distributed in an automated fashion to this newly added node until I re-create the pods. So I have been searching for the automated mechanism which can distribute the running pods across the nodes and I came across this project but I see this is still in incubator state so I cannot use this on my AWS EKS infrastructure until it is released, so my questions are:

1. When is this project set to release? and in which version can we expect this?
2. Until it is released, is there any alternative way we could achieve this, pods distribution to the new nodes?(cluster version is 1.12)

Any inputs are very much appreciated. Thank you.

**Comment by aveshagarwal** [comment]
Descheduler is an add-on for kubernetes, so there is no plan to add it to core kubernetes project. See the README file that tells how to deploy it with k8s clusters.

**Comment by chandrakanthkannam** [comment]
Thank you @aveshagarwal for the response.
But my cluster is running on AWS EKS and the master nodes are managed by AWS. so in this scenario can i use these add-on or Do i have to put request to AWS to add these to master?
