### ISSUE TITLE
Test logic for duplicates can be improved

### ISSUE THREAD

**Issue by tammert** [kubernetes-incubator/descheduler#157]
While adding a test for PR #156 is noticed the test logic in `duplicates_test.go` is slightly flawed. Currently, a lot of different tests are performed and only the cumulative result is considered. By doing this, if two tests fail (one Pod that should not be evicted *is*, and a Pod that should be evicted *is not*) they could cancel each other out so the test would pass when it should not.

I would suggest rewriting the tests so that each individual scenario is run and considered separately. If you agree, I'd be happy to do this so you can assign this to me.

**Comment by aveshagarwal** [comment]
@tammert sounds good to me. feel free to send a PR.

**Comment by tammert** [comment]
So @reetasingh already picked up part of this issue by making the tests table driven (thanks for that!). I'll open a PR that streamlines the logic a little further.
