### ISSUE TITLE
Question: pods under load

### ISSUE THREAD

**Issue by Boojs** [kubernetes-incubator/descheduler#170]
Hi, I am just wondering what would happen in the event when pods are under load. Specifically talking about **RemovePodsViolatingInterPodAntiAffinity** and **RemovePodsViolatingNodeAffinity** . 

Normally I have 3 pods across 3 nodes, but can burst to 10-15pods on those 3 nodes if needed. If the descheduler would run at that time, I assume it would deschedule a bunch of those pods back down to 3?

After that, the deployment would kick in again and scale back to necessary amount of pods to handle the load.

**Comment by aveshagarwal** [comment]
> Hi, I am just wondering what would happen in the event when pods are under load. Specifically talking about **RemovePodsViolatingInterPodAntiAffinity** and **RemovePodsViolatingNodeAffinity** .
> 
> Normally I have 3 pods across 3 nodes, but can burst to 10-15pods on those 3 nodes if needed. If the descheduler would run at that time, I assume it would deschedule a bunch of those pods back down to 3?
> 

Descheduler actually does not scale down, it would kill/evict pods violating pod or node affinity. And their controller would recreate somewhere else.

> After that, the deployment would kick in again and scale back to necessary amount of pods to handle the load.

Yes. So it seems in your scenario, you could disable those affinity strategies, as otherwise descheduler and the controller could go into loop.

**Comment by Boojs** [comment]
Thank you for the clarification @aveshagarwal
