### ISSUE TITLE
Add an Ascii-art [before/after] diagram and fix some typos in the rescheduler README.md

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-incubator/descheduler#2]
This is just a starter issue to get ramped up on contributing.  Its been a while since I've contributed anything to upstream :). 

For this issue we'd like to:

- Update an ascii diagram of before/after a rescheduling scenario (specifically, one for the low node usage / bin packing, as thats strategic for us at this time).
- Fix some minor nits and typos in the README.md.

**Comment by ravisantoshgudimetla** [comment]
@jayunit100 - Is this something that you want to pick up? I believe the ascii part is remaining.
