### ISSUE TITLE
Usage with Openshift

### ISSUE THREAD

**Issue by thorstenstahl** [kubernetes-incubator/descheduler#32]
It would be very helpfull to get a documentation about how to use and setup the descheduler job within a openshift environment.

I tried to follow the README within my openshift cluster but when creating the ClusterRole i get the following error:
error: unable to recognize "STDIN": no matches for rbac.authorization.k8s.io/, Kind=ClusterRole

When calling the "make" on my MAC OS or CENTOS also the build fails:

go build -ldflags "-X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.version=`git describe --tags` -X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.buildDate=`date +%FT%T%z` -X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.gitCommit=`git rev-parse HEAD`" -o _output/bin/descheduler github.com/kubernetes-incubator/descheduler/cmd/descheduler

**Comment by aveshagarwal** [comment]
@thorstenstahl what version of openshift and centos you are testing with?

**Comment by aveshagarwal** [comment]
@thorstenstahl for first issue related to cluster role: change to `apiVersion: v1`

**Comment by aveshagarwal** [comment]
for compile issue, could you send full error logs you are seeing?

**Comment by thorstenstahl** [comment]
oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server ***
openshift v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4

**Comment by thorstenstahl** [comment]
msarcher-macbook-pro:descheduler msarcher$ make
go build -ldflags "-X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.version=`git describe --tags` -X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.buildDate=`date +%FT%T%z` -X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.gitCommit=`git rev-parse HEAD`" -o _output/bin/descheduler github.com/kubernetes-incubator/descheduler/cmd/descheduler 
can't load package: package github.com/kubernetes-incubator/descheduler/cmd/descheduler: cannot find package "github.com/kubernetes-incubator/descheduler/cmd/descheduler" in any of:
	/usr/local/Cellar/go/1.9.2/libexec/src/github.com/kubernetes-incubator/descheduler/cmd/descheduler (from $GOROOT)
	/Users/msarcher/go/src/github.com/kubernetes-incubator/descheduler/cmd/descheduler (from $GOPATH)
make: *** [build] Error 1

**Comment by msa0311** [comment]
CentOS Linux release 7.3.1611 (Core)

**Comment by aveshagarwal** [comment]
Thanks.

> oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4oc v1.5.0+031cbe4

It is supposed to work for 1.7+, but lets try.

> error: unable to recognize "STDIN": no matches for rbac.authorization.k8s.io/, Kind=ClusterRole

As I commented above change to `apiVersion: v1`

>msarcher-macbook-pro:descheduler msarcher$ make
go build -ldflags "-X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.version=git describe --tags -X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.buildDate=date +%FT%T%z -X github.com/kubernetes-incubator/descheduler/cmd/descheduler/app.gitCommit=git rev-parse HEAD" -o _output/bin/descheduler github.com/kubernetes-incubator/descheduler/cmd/descheduler
can't load package: package github.com/kubernetes-incubator/descheduler/cmd/descheduler: cannot find package "github.com/kubernetes-incubator/descheduler/cmd/descheduler" in any of:
/usr/local/Cellar/go/1.9.2/libexec/src/github.com/kubernetes-incubator/descheduler/cmd/descheduler (from $GOROOT)
/Users/msarcher/go/src/github.com/kubernetes-incubator/descheduler/cmd/descheduler (from $GOPATH)
make: *** [build] Error 1


What is your GOPATH? does this `/Users/msarcher/go/src/github.com/kubernetes-incubator/descheduler/` exist?

**Comment by aveshagarwal** [comment]
@thorstenstahl is it ok to close this if your issue is resolved?

**Comment by msa0311** [comment]
Was able to deploy descheduler in openshift with some manual effort. Also created a tempalte for pushing it using the openshift UI / console. 

Thanks for your support.

**Comment by aveshagarwal** [comment]
@msa0311 thanks,  could you share your template here? Also could you explain what you mean by "with some manual" effort? I'd happy to look into if it is possible to reduce some manual steps.  Also let me know if you run into any other issues.

**Comment by ravisantoshgudimetla** [comment]
@msa0311 . I am closing this issue as it is resolved. Please feel free to re-open this.

**Comment by FKatenbrink** [comment]
I am having the same issue as @ThorstenStahl on OSX. @msa0311 could you provide your template?
