### ISSUE TITLE
Unable to specify only one or two of cpu, memory or pods for LowNodeUtilization

### ISSUE THREAD

**Issue by containscafeine** [kubernetes-incubator/descheduler#38]
Hi,
I was just playing around with the project.

My policy file looks like -
```yaml
apiVersion: "descheduler/v1alpha1"
kind: "DeschedulerPolicy"
strategies:
  "LowNodeUtilization":
     enabled: true
     params:
       nodeResourceUtilizationThresholds:
         thresholds:
           "cpu" : 20
         targetThresholds:
           "cpu" : 50
```

and I run the descheduler like -
```console
$ _output/bin/descheduler --kubeconfig-file /var/run/kubernetes/admin.kubeconfig --policy-config-file examples/policy.yaml  -v 5
I1123 17:14:37.581631   13825 reflector.go:198] Starting reflector *v1.Node (1h0m0s) from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:83
I1123 17:14:37.581785   13825 node.go:50] node lister returned empty list, now fetch directly
I1123 17:14:37.582104   13825 reflector.go:236] Listing and watching *v1.Node from github.com/kubernetes-incubator/descheduler/pkg/descheduler/node/node.go:83
I1123 17:14:38.069287   13825 lownodeutilization.go:104] no target resource threshold for pods is configured
```

The exit code is 0, but I'm not sure if the descheduler actually went ahead and processed the nodes, etc, because it might have stopped while seeing that there is no `targetThreshold` for pods.

If this is the case, does it make sense to make all the 3 parameters, pods, memory and cpu, mandatory for the descheduler to take decisions, why can I not set the parameter to just cpu, or memory, or pods.

Does this make sense?

**Comment by aveshagarwal** [comment]
@containscafeine the idea is to specify `atleast` one of them. Previously it was just number of pods as the algorithm mainly worked based on number of pods threshold.  But now the algorithm takes all cpu, mem, and number of pods into account, so atleast one should be specified. Is it not happening?

**Comment by containscafeine** [comment]
@aveshagarwal works for me now when I run against a v1.8.4 kube cluster, did not work against master. Going to close this. Sorry for the noise :)
