### ISSUE TITLE
Why not be a cron job for descheduler?

### ISSUE THREAD

**Issue by wjiangjay** [kubernetes-incubator/descheduler#50]
I go through the README and found that the descheduler is deployed as a job on kubernetes, and it only exec once. 

So why not be a cron job?

Ref: 
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by ravisantoshgudimetla** [comment]
@wjiangjay We didn't put up a table for supported versions of descheduler on github but as of now, descheduler works with 1.7 and 1.8.

**Comment by ravisantoshgudimetla** [comment]
Since descheduler is destructive in nature, we recommend to use it as a job and use dry-run before actual running. If we don't care much about the pods that are being evicted, we can run it as a cron job as well.

**Comment by aveshagarwal** [comment]
@wjiangjay descheduler as a job is just one way of running it. You can always run descheduler as a cron job to activate it on a regular interval.

**Comment by ravisantoshgudimetla** [comment]
@wjiangjay Can we close this issue?

**Comment by wjiangjay** [comment]
yeah @ravisantoshgudimetla
