### ISSUE TITLE
PVC Consideration

### ISSUE THREAD

**Issue by jrnt30** [kubernetes-incubator/descheduler#6]
Project looks interesting!  One consideration on the "Future Roadmap" that would be worth considering is the Fault Domains and the PVCs that are associated with a pod.  

"Evicting" the pod with a PVC due to LowNodeUtilization on another node would not result in actual re-placement of that pod, so it shouldn't be attempted.

**Comment by ravisantoshgudimetla** [comment]
@jrnt30 - Eviction of pod with a PVC seems unreasonable as this may  cause data loss.  So, descheduler should not do this.

**Comment by jrnt30** [comment]
Thanks for the response.  To be a bit more clear about what I was hoping to resolve is: 

- Descheduler sees a node is Under Utilized and wants to evict pods 
- Pods are descheduled from nodes
- A specific pod (such as one in a stateful set or with a PVC) has a volume associated with it however there is no excess capacity on any nodes in the same fault domain (AWS AZ, Azure Zone, etc.) so the K8 Scheduler is unable at actually place the Pod again 

At this point either a smart cluster autoscaler or operator would need to get involved to either uncordon the node or create a new node in the proper AZ to provide adequate headroom to place the pod again.

**Comment by ravisantoshgudimetla** [comment]
Thanks for providing the entire use-case.

> Pods are descheduled from nodes

I believe this shouldn't happen in first place.
