### ISSUE TITLE
Terminology confusion around utilization

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes-incubator/descheduler#7]
The current configuration types describe `NodeResourceUtilizationThresholds`.

I think utilization implies observed usage, not what is scheduled or allocated.

If we use the term utilization, it should mean the decision is based on metrics.

If we use the term allocated or node scheduling thresholds, it should mean the decision is based on pod resource requests, and not observed usage.

**Comment by ravisantoshgudimetla** [comment]
> If we use the term utilization, it should mean the decision is based on metrics.

I think, once we move to metrics based decision making, the terminology would make sense.
